'use strict';

const { describe, it, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert');
const { mkdtempSync, writeFileSync, mkdirSync, rmSync, readFileSync, existsSync } = require('fs');
const { join } = require('path');
const { execSync } = require('child_process');
const { tmpdir } = require('os');

const LOADER = join(__dirname, '..', 'bin', 'loader.sh');

function runLoader(projectDir, env = {}) {
  try {
    return execSync(`bash "${LOADER}"`, {
      encoding: 'utf8',
      env: { ...process.env, CLAUDE_PROJECT_DIR: projectDir, ...env },
      timeout: 5000
    });
  } catch (err) {
    return err.stdout || '';
  }
}

function createGitRepo() {
  const dir = mkdtempSync(join(tmpdir(), 'agents-md-test-'));
  execSync('git init', { cwd: dir, stdio: 'pipe' });
  execSync('git config user.name "test"', { cwd: dir, stdio: 'pipe' });
  execSync('git config user.email "test@test.com"', { cwd: dir, stdio: 'pipe' });
  return dir;
}

function readGenerated(root) {
  const target = join(root, '.claude', 'CLAUDE.md');
  return existsSync(target) ? readFileSync(target, 'utf8') : null;
}

describe('loader.sh', () => {
  let tmpDir;

  beforeEach(() => {
    tmpDir = createGitRepo();
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  it('outputs nothing and generates no file when no AGENTS.md exists', () => {
    const output = runLoader(tmpDir);
    assert.strictEqual(output.trim(), '');
    assert.strictEqual(readGenerated(tmpDir), null);
  });

  it('generates .claude/CLAUDE.md with root AGENTS.md content', () => {
    writeFileSync(join(tmpDir, 'AGENTS.md'), '# Root instructions\nDo things.');
    const output = runLoader(tmpDir);

    assert.ok(output.includes('[cc-agents-md]'), 'Should have status line');
    const generated = readGenerated(tmpDir);
    assert.ok(generated !== null, '.claude/CLAUDE.md should exist');
    assert.ok(generated.includes('Auto-generated by cc-agents-md'), 'Should have auto-generated header');
    assert.ok(generated.includes('# AGENTS.md'), 'Should have section header');
    assert.ok(generated.includes('Root instructions'), 'Should include content');
    assert.ok(generated.includes('Do things.'), 'Should include full content');
  });

  it('generates .claude/CLAUDE.md with nested files root-first', () => {
    writeFileSync(join(tmpDir, 'AGENTS.md'), '# Root instructions');
    const subDir = join(tmpDir, 'packages', 'frontend');
    mkdirSync(subDir, { recursive: true });
    writeFileSync(join(subDir, 'AGENTS.md'), '# Frontend rules');

    runLoader(subDir);
    const generated = readGenerated(tmpDir);
    const rootIdx = generated.indexOf('Root instructions');
    const frontendIdx = generated.indexOf('Frontend rules');
    assert.ok(rootIdx >= 0, 'Root AGENTS.md should be present');
    assert.ok(frontendIdx >= 0, 'Frontend AGENTS.md should be present');
    assert.ok(rootIdx < frontendIdx, 'Root should come before nested');
  });

  it('does not include sibling directory AGENTS.md', () => {
    writeFileSync(join(tmpDir, 'AGENTS.md'), '# Root instructions');
    const frontendDir = join(tmpDir, 'packages', 'frontend');
    mkdirSync(frontendDir, { recursive: true });
    writeFileSync(join(frontendDir, 'AGENTS.md'), '# Frontend rules');
    const backendDir = join(tmpDir, 'packages', 'backend');
    mkdirSync(backendDir, { recursive: true });
    writeFileSync(join(backendDir, 'AGENTS.md'), '# Backend rules');

    runLoader(frontendDir);
    const generated = readGenerated(tmpDir);
    assert.ok(!generated.includes('Backend rules'), 'Sibling AGENTS.md must NOT be loaded');
  });

  it('loads full content regardless of size', () => {
    const bigContent = Array(10000).fill('line of content').join('\n');
    writeFileSync(join(tmpDir, 'AGENTS.md'), bigContent);

    runLoader(tmpDir);
    const generated = readGenerated(tmpDir);
    assert.ok(generated !== null, '.claude/CLAUDE.md should exist');
    assert.strictEqual(generated.split('line of content').length - 1, 10000, 'All 10000 lines should be present');
  });

  it('cleans up stale .claude/CLAUDE.md when no AGENTS.md exists', () => {
    // Create a generated file as if a previous run created it
    mkdirSync(join(tmpDir, '.claude'), { recursive: true });
    writeFileSync(join(tmpDir, '.claude', 'CLAUDE.md'), '<!-- Auto-generated by cc-agents-md. Do not edit. -->\n# old');

    runLoader(tmpDir);
    assert.strictEqual(readGenerated(tmpDir), null, 'Stale file should be removed');
  });

  it('does not remove user-created .claude/CLAUDE.md', () => {
    mkdirSync(join(tmpDir, '.claude'), { recursive: true });
    writeFileSync(join(tmpDir, '.claude', 'CLAUDE.md'), '# My custom instructions');

    runLoader(tmpDir);
    const content = readGenerated(tmpDir);
    assert.ok(content.includes('My custom instructions'), 'User file should be preserved');
  });

  it('works without a git repo', () => {
    const noGitDir = mkdtempSync(join(tmpdir(), 'agents-md-nogit-'));
    writeFileSync(join(noGitDir, 'AGENTS.md'), '# No git here');

    runLoader(noGitDir);
    const generated = readGenerated(noGitDir);
    assert.ok(generated !== null, '.claude/CLAUDE.md should exist');
    assert.ok(generated.includes('No git here'), 'Should load AGENTS.md without git');

    rmSync(noGitDir, { recursive: true, force: true });
  });

  it('exits silently on invalid project dir', () => {
    const output = runLoader('/nonexistent/path/that/does/not/exist');
    assert.strictEqual(output.trim(), '');
  });

  it('status output lists found files', () => {
    writeFileSync(join(tmpDir, 'AGENTS.md'), '# Root');
    const subDir = join(tmpDir, 'sub');
    mkdirSync(subDir);
    writeFileSync(join(subDir, 'AGENTS.md'), '# Sub');

    const output = runLoader(subDir);
    assert.ok(output.includes('2 AGENTS.md file(s)'), 'Should report count');
    assert.ok(output.includes('AGENTS.md'), 'Should list files');
  });
});
